[package]
name = "netstack3-port-integration"
edition.workspace = true
license = "MIT OR Apache-2.0 AND BSD-2-Clause"
version.workspace = true
publish = false

[dependencies]
dhcp_client_core.workspace = true
async-trait.workspace = true
dhcp_protocol.workspace = true
diagnostics_traits.workspace = true
futures.workspace = true
futures-io.workspace = true
trust-dns-proto.workspace = true
trust-dns-resolver.workspace = true
netstack3-port-spike = { path = "../../../../../../../../crates/netstack3-port-spike" }
netstack3_core = { path = "../../core" }
net_types.workspace = true
net_declare.workspace = true
netstack3_base.workspace = true
netstack3_device.workspace = true
netstack3_filter.workspace = true
netstack3_icmp_echo.workspace = true
netstack3_udp.workspace = true
packet.workspace = true
packet_formats.workspace = true
netstack3_tcp.workspace = true
netstack3_ip.workspace = true
rand.workspace = true
zerocopy.workspace = true

[dev-dependencies]
netstack3_core = { path = "../../core", features = ["testutils"] }
