[package]
name = "fuchsia-inspect-contrib"
workspace = "../../../../../connectivity/network/netstack3"
version.workspace = true
edition.workspace = true
license = "MIT OR Apache-2.0"

[lib]
name = "fuchsia_inspect_contrib"
path = "host/src/lib.rs"
doctest = false

[dependencies]
fuchsia-inspect = { path = "../../rust" }
zx = { path = "../../../../../../sdk/rust/zx" }
