[package]
name = "eapol"
workspace = "../../../network/netstack3"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
path = "src/lib.rs"

[features]
benchmarks = []

[dependencies]
anyhow.workspace = true
log.workspace = true
thiserror.workspace = true
wlan-common = { path = "../common/rust" }
wlan_bitfield.workspace = true
zerocopy.workspace = true

[dev-dependencies]
assert_matches.workspace = true
