[package]
name = "dhcp_client_core"
workspace = "../../../netstack3"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
bstr.workspace = true
derive_builder.workspace = true
dhcp_protocol.workspace = true
diagnostics_traits.workspace = true
futures.workspace = true
log.workspace = true
net_types.workspace = true
packet.workspace = true
packet_formats.workspace = true
rand.workspace = true
thiserror.workspace = true

[dev-dependencies]
assert_matches.workspace = true
net_declare.workspace = true
