[package]
name = "fidl-fuchsia-wlan-driver"
workspace = "../../../src/connectivity/network/netstack3"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "fidl_fuchsia_wlan_driver"
path = "src/lib.rs"
doctest = false

[dependencies]
fidl-fuchsia-wlan-ieee80211 = { path = "../fuchsia.wlan.ieee80211" }
