[package]
name = "fidl-fuchsia-wlan-softmac"
workspace = "../../../src/connectivity/network/netstack3"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "fidl_fuchsia_wlan_softmac"
path = "src/lib.rs"

[dependencies]
bitflags.workspace = true
fidl-fuchsia-wlan-common = { path = "../fuchsia.wlan.common" }
fidl-fuchsia-wlan-driver = { path = "../fuchsia.wlan.driver" }
fidl-fuchsia-wlan-ieee80211 = { path = "../fuchsia.wlan.ieee80211" }
