[package]
name = "amd-hda-spike"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
drv-audio-pipewire-spike = { path = "../audio-pipewire-spike" }
drv-fuchsia-audio-processing = { path = "../fuchsia-audio-processing" }

[[bin]]
name = "amd-hda-enumerate"
path = "src/main.rs"
