[package]
name="ath11k-core"
version.workspace=true
edition.workspace=true
license.workspace=true
[dependencies]
ath11k-platform-backend={path="../ath11k-platform-backend"}
ath11k-hal={path="../ath11k-hal"}
ath11k-ce={path="../ath11k-ce"}
ath11k-qmi={path="../ath11k-qmi"}
ath11k-wmi={path="../ath11k-wmi"}
ath11k-dp={path="../ath11k-dp"}
sha2 = { version = "0.11", default-features = false }
[dev-dependencies]
drv-hardware-backends={path="../../../../platform/hardware-backends"}
