// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod drv {
    pub mod hardware {
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod broker {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum Error {
                Invalid,
                StaleHandle,
                OutOfBounds,
                Limit,
                Cancelled,
                DeviceFault,
            }
            impl Error {
                pub fn name(&self) -> &'static str {
                    match self {
                        Error::Invalid => "invalid",
                        Error::StaleHandle => "stale-handle",
                        Error::OutOfBounds => "out-of-bounds",
                        Error::Limit => "limit",
                        Error::Cancelled => "cancelled",
                        Error::DeviceFault => "device-fault",
                    }
                }
                pub fn message(&self) -> &'static str {
                    match self {
                        Error::Invalid => "",
                        Error::StaleHandle => "",
                        Error::OutOfBounds => "",
                        Error::Limit => "",
                        Error::Cancelled => "",
                        Error::DeviceFault => "",
                    }
                }
            }
            impl ::core::fmt::Debug for Error {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("Error")
                        .field("code", &(*self as i32))
                        .field("name", &self.name())
                        .field("message", &self.message())
                        .finish()
                }
            }
            impl ::core::fmt::Display for Error {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    write!(f, "{} (error {})", self.name(), * self as i32)
                }
            }
            impl std::error::Error for Error {}
            impl Error {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> Error {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => Error::Invalid,
                        1 => Error::StaleHandle,
                        2 => Error::OutOfBounds,
                        3 => Error::Limit,
                        4 => Error::Cancelled,
                        5 => Error::DeviceFault,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum DmaAccess {
                DeviceRead,
                DeviceWrite,
                Bidirectional,
            }
            impl ::core::fmt::Debug for DmaAccess {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        DmaAccess::DeviceRead => {
                            f.debug_tuple("DmaAccess::DeviceRead").finish()
                        }
                        DmaAccess::DeviceWrite => {
                            f.debug_tuple("DmaAccess::DeviceWrite").finish()
                        }
                        DmaAccess::Bidirectional => {
                            f.debug_tuple("DmaAccess::Bidirectional").finish()
                        }
                    }
                }
            }
            impl DmaAccess {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> DmaAccess {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => DmaAccess::DeviceRead,
                        1 => DmaAccess::DeviceWrite,
                        2 => DmaAccess::Bidirectional,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            #[repr(C)]
            #[derive(Clone, Copy)]
            pub struct IrqEvent {
                pub vector: u32,
                pub count: u64,
                pub at_ns: u64,
            }
            impl ::core::fmt::Debug for IrqEvent {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("IrqEvent")
                        .field("vector", &self.vector)
                        .field("count", &self.count)
                        .field("at-ns", &self.at_ns)
                        .finish()
                }
            }
            #[derive(Debug)]
            #[repr(transparent)]
            pub struct Region {
                handle: _rt::Resource<Region>,
            }
            impl Region {
                #[doc(hidden)]
                pub unsafe fn from_handle(handle: u32) -> Self {
                    Self {
                        handle: unsafe { _rt::Resource::from_handle(handle) },
                    }
                }
                #[doc(hidden)]
                pub fn take_handle(&self) -> u32 {
                    _rt::Resource::take_handle(&self.handle)
                }
                #[doc(hidden)]
                pub fn handle(&self) -> u32 {
                    _rt::Resource::handle(&self.handle)
                }
            }
            unsafe impl _rt::WasmResource for Region {
                #[inline]
                unsafe fn drop(_handle: u32) {
                    #[cfg(not(target_arch = "wasm32"))]
                    unreachable!();
                    #[cfg(target_arch = "wasm32")]
                    {
                        #[link(wasm_import_module = "drv:hardware/broker@0.1.0")]
                        unsafe extern "C" {
                            #[link_name = "[resource-drop]region"]
                            fn drop(_: u32);
                        }
                        unsafe { drop(_handle) };
                    }
                }
            }
            #[derive(Debug)]
            #[repr(transparent)]
            pub struct DmaArena {
                handle: _rt::Resource<DmaArena>,
            }
            impl DmaArena {
                #[doc(hidden)]
                pub unsafe fn from_handle(handle: u32) -> Self {
                    Self {
                        handle: unsafe { _rt::Resource::from_handle(handle) },
                    }
                }
                #[doc(hidden)]
                pub fn take_handle(&self) -> u32 {
                    _rt::Resource::take_handle(&self.handle)
                }
                #[doc(hidden)]
                pub fn handle(&self) -> u32 {
                    _rt::Resource::handle(&self.handle)
                }
            }
            unsafe impl _rt::WasmResource for DmaArena {
                #[inline]
                unsafe fn drop(_handle: u32) {
                    #[cfg(not(target_arch = "wasm32"))]
                    unreachable!();
                    #[cfg(target_arch = "wasm32")]
                    {
                        #[link(wasm_import_module = "drv:hardware/broker@0.1.0")]
                        unsafe extern "C" {
                            #[link_name = "[resource-drop]dma-arena"]
                            fn drop(_: u32);
                        }
                        unsafe { drop(_handle) };
                    }
                }
            }
            #[derive(Debug)]
            #[repr(transparent)]
            pub struct Interrupt {
                handle: _rt::Resource<Interrupt>,
            }
            impl Interrupt {
                #[doc(hidden)]
                pub unsafe fn from_handle(handle: u32) -> Self {
                    Self {
                        handle: unsafe { _rt::Resource::from_handle(handle) },
                    }
                }
                #[doc(hidden)]
                pub fn take_handle(&self) -> u32 {
                    _rt::Resource::take_handle(&self.handle)
                }
                #[doc(hidden)]
                pub fn handle(&self) -> u32 {
                    _rt::Resource::handle(&self.handle)
                }
            }
            unsafe impl _rt::WasmResource for Interrupt {
                #[inline]
                unsafe fn drop(_handle: u32) {
                    #[cfg(not(target_arch = "wasm32"))]
                    unreachable!();
                    #[cfg(target_arch = "wasm32")]
                    {
                        #[link(wasm_import_module = "drv:hardware/broker@0.1.0")]
                        unsafe extern "C" {
                            #[link_name = "[resource-drop]interrupt"]
                            fn drop(_: u32);
                        }
                        unsafe { drop(_handle) };
                    }
                }
            }
            #[derive(Debug)]
            #[repr(transparent)]
            pub struct Device {
                handle: _rt::Resource<Device>,
            }
            impl Device {
                #[doc(hidden)]
                pub unsafe fn from_handle(handle: u32) -> Self {
                    Self {
                        handle: unsafe { _rt::Resource::from_handle(handle) },
                    }
                }
                #[doc(hidden)]
                pub fn take_handle(&self) -> u32 {
                    _rt::Resource::take_handle(&self.handle)
                }
                #[doc(hidden)]
                pub fn handle(&self) -> u32 {
                    _rt::Resource::handle(&self.handle)
                }
            }
            unsafe impl _rt::WasmResource for Device {
                #[inline]
                unsafe fn drop(_handle: u32) {
                    #[cfg(not(target_arch = "wasm32"))]
                    unreachable!();
                    #[cfg(target_arch = "wasm32")]
                    {
                        #[link(wasm_import_module = "drv:hardware/broker@0.1.0")]
                        unsafe extern "C" {
                            #[link_name = "[resource-drop]device"]
                            fn drop(_: u32);
                        }
                        unsafe { drop(_handle) };
                    }
                }
            }
            impl Region {
                #[allow(unused_unsafe, clippy::all)]
                pub fn read_u32(&self, offset: u32) -> Result<u32, Error> {
                    unsafe {
                        #[repr(align(4))]
                        struct RetArea([::core::mem::MaybeUninit<u8>; 8]);
                        let mut ret_area = RetArea(
                            [::core::mem::MaybeUninit::uninit(); 8],
                        );
                        let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
                        #[cfg(target_arch = "wasm32")]
                        #[link(wasm_import_module = "drv:hardware/broker@0.1.0")]
                        unsafe extern "C" {
                            #[link_name = "[method]region.read-u32"]
                            fn wit_import1(_: i32, _: i32, _: *mut u8);
                        }
                        #[cfg(not(target_arch = "wasm32"))]
                        unsafe extern "C" fn wit_import1(_: i32, _: i32, _: *mut u8) {
                            unreachable!()
                        }
                        unsafe {
                            wit_import1(
                                (self).handle() as i32,
                                _rt::as_i32(&offset),
                                ptr0,
                            )
                        };
                        let l2 = i32::from(*ptr0.add(0).cast::<u8>());
                        let result5 = match l2 {
                            0 => {
                                let e = {
                                    let l3 = *ptr0.add(4).cast::<i32>();
                                    l3 as u32
                                };
                                Ok(e)
                            }
                            1 => {
                                let e = {
                                    let l4 = i32::from(*ptr0.add(4).cast::<u8>());
                                    Error::_lift(l4 as u8)
                                };
                                Err(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        };
                        result5
                    }
                }
            }
            impl Region {
                #[allow(unused_unsafe, clippy::all)]
                pub fn write_u32(&self, offset: u32, value: u32) -> Result<(), Error> {
                    unsafe {
                        #[repr(align(1))]
                        struct RetArea([::core::mem::MaybeUninit<u8>; 2]);
                        let mut ret_area = RetArea(
                            [::core::mem::MaybeUninit::uninit(); 2],
                        );
                        let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
                        #[cfg(target_arch = "wasm32")]
                        #[link(wasm_import_module = "drv:hardware/broker@0.1.0")]
                        unsafe extern "C" {
                            #[link_name = "[method]region.write-u32"]
                            fn wit_import1(_: i32, _: i32, _: i32, _: *mut u8);
                        }
                        #[cfg(not(target_arch = "wasm32"))]
                        unsafe extern "C" fn wit_import1(
                            _: i32,
                            _: i32,
                            _: i32,
                            _: *mut u8,
                        ) {
                            unreachable!()
                        }
                        unsafe {
                            wit_import1(
                                (self).handle() as i32,
                                _rt::as_i32(&offset),
                                _rt::as_i32(&value),
                                ptr0,
                            )
                        };
                        let l2 = i32::from(*ptr0.add(0).cast::<u8>());
                        let result4 = match l2 {
                            0 => {
                                let e = ();
                                Ok(e)
                            }
                            1 => {
                                let e = {
                                    let l3 = i32::from(*ptr0.add(1).cast::<u8>());
                                    Error::_lift(l3 as u8)
                                };
                                Err(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        };
                        result4
                    }
                }
            }
            impl DmaArena {
                #[allow(unused_unsafe, clippy::all)]
                pub fn length(&self) -> Result<u32, Error> {
                    unsafe {
                        #[repr(align(4))]
                        struct RetArea([::core::mem::MaybeUninit<u8>; 8]);
                        let mut ret_area = RetArea(
                            [::core::mem::MaybeUninit::uninit(); 8],
                        );
                        let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
                        #[cfg(target_arch = "wasm32")]
                        #[link(wasm_import_module = "drv:hardware/broker@0.1.0")]
                        unsafe extern "C" {
                            #[link_name = "[method]dma-arena.length"]
                            fn wit_import1(_: i32, _: *mut u8);
                        }
                        #[cfg(not(target_arch = "wasm32"))]
                        unsafe extern "C" fn wit_import1(_: i32, _: *mut u8) {
                            unreachable!()
                        }
                        unsafe { wit_import1((self).handle() as i32, ptr0) };
                        let l2 = i32::from(*ptr0.add(0).cast::<u8>());
                        let result5 = match l2 {
                            0 => {
                                let e = {
                                    let l3 = *ptr0.add(4).cast::<i32>();
                                    l3 as u32
                                };
                                Ok(e)
                            }
                            1 => {
                                let e = {
                                    let l4 = i32::from(*ptr0.add(4).cast::<u8>());
                                    Error::_lift(l4 as u8)
                                };
                                Err(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        };
                        result5
                    }
                }
            }
            impl DmaArena {
                #[allow(unused_unsafe, clippy::all)]
                pub fn iova(&self) -> Result<u64, Error> {
                    unsafe {
                        #[repr(align(8))]
                        struct RetArea([::core::mem::MaybeUninit<u8>; 16]);
                        let mut ret_area = RetArea(
                            [::core::mem::MaybeUninit::uninit(); 16],
                        );
                        let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
                        #[cfg(target_arch = "wasm32")]
                        #[link(wasm_import_module = "drv:hardware/broker@0.1.0")]
                        unsafe extern "C" {
                            #[link_name = "[method]dma-arena.iova"]
                            fn wit_import1(_: i32, _: *mut u8);
                        }
                        #[cfg(not(target_arch = "wasm32"))]
                        unsafe extern "C" fn wit_import1(_: i32, _: *mut u8) {
                            unreachable!()
                        }
                        unsafe { wit_import1((self).handle() as i32, ptr0) };
                        let l2 = i32::from(*ptr0.add(0).cast::<u8>());
                        let result5 = match l2 {
                            0 => {
                                let e = {
                                    let l3 = *ptr0.add(8).cast::<i64>();
                                    l3 as u64
                                };
                                Ok(e)
                            }
                            1 => {
                                let e = {
                                    let l4 = i32::from(*ptr0.add(8).cast::<u8>());
                                    Error::_lift(l4 as u8)
                                };
                                Err(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        };
                        result5
                    }
                }
            }
            impl DmaArena {
                #[allow(unused_unsafe, clippy::all)]
                pub fn read(
                    &self,
                    offset: u32,
                    length: u32,
                ) -> Result<_rt::Vec<u8>, Error> {
                    unsafe {
                        #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                        #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                        struct RetArea(
                            [::core::mem::MaybeUninit<
                                u8,
                            >; 3 * ::core::mem::size_of::<*const u8>()],
                        );
                        let mut ret_area = RetArea(
                            [::core::mem::MaybeUninit::uninit(); 3
                                * ::core::mem::size_of::<*const u8>()],
                        );
                        let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
                        #[cfg(target_arch = "wasm32")]
                        #[link(wasm_import_module = "drv:hardware/broker@0.1.0")]
                        unsafe extern "C" {
                            #[link_name = "[method]dma-arena.read"]
                            fn wit_import1(_: i32, _: i32, _: i32, _: *mut u8);
                        }
                        #[cfg(not(target_arch = "wasm32"))]
                        unsafe extern "C" fn wit_import1(
                            _: i32,
                            _: i32,
                            _: i32,
                            _: *mut u8,
                        ) {
                            unreachable!()
                        }
                        unsafe {
                            wit_import1(
                                (self).handle() as i32,
                                _rt::as_i32(&offset),
                                _rt::as_i32(&length),
                                ptr0,
                            )
                        };
                        let l2 = i32::from(*ptr0.add(0).cast::<u8>());
                        let result7 = match l2 {
                            0 => {
                                let e = {
                                    let l3 = *ptr0
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l4 = *ptr0
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    let len5 = l4;
                                    _rt::Vec::from_raw_parts(l3.cast(), len5, len5)
                                };
                                Ok(e)
                            }
                            1 => {
                                let e = {
                                    let l6 = i32::from(
                                        *ptr0.add(::core::mem::size_of::<*const u8>()).cast::<u8>(),
                                    );
                                    Error::_lift(l6 as u8)
                                };
                                Err(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        };
                        result7
                    }
                }
            }
            impl DmaArena {
                #[allow(unused_unsafe, clippy::all)]
                pub fn write(&self, offset: u32, bytes: &[u8]) -> Result<(), Error> {
                    unsafe {
                        #[repr(align(1))]
                        struct RetArea([::core::mem::MaybeUninit<u8>; 2]);
                        let mut ret_area = RetArea(
                            [::core::mem::MaybeUninit::uninit(); 2],
                        );
                        let vec0 = bytes;
                        let ptr0 = vec0.as_ptr().cast::<u8>();
                        let len0 = vec0.len();
                        let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
                        #[cfg(target_arch = "wasm32")]
                        #[link(wasm_import_module = "drv:hardware/broker@0.1.0")]
                        unsafe extern "C" {
                            #[link_name = "[method]dma-arena.write"]
                            fn wit_import2(
                                _: i32,
                                _: i32,
                                _: *mut u8,
                                _: usize,
                                _: *mut u8,
                            );
                        }
                        #[cfg(not(target_arch = "wasm32"))]
                        unsafe extern "C" fn wit_import2(
                            _: i32,
                            _: i32,
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                        ) {
                            unreachable!()
                        }
                        unsafe {
                            wit_import2(
                                (self).handle() as i32,
                                _rt::as_i32(&offset),
                                ptr0.cast_mut(),
                                len0,
                                ptr1,
                            )
                        };
                        let l3 = i32::from(*ptr1.add(0).cast::<u8>());
                        let result5 = match l3 {
                            0 => {
                                let e = ();
                                Ok(e)
                            }
                            1 => {
                                let e = {
                                    let l4 = i32::from(*ptr1.add(1).cast::<u8>());
                                    Error::_lift(l4 as u8)
                                };
                                Err(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        };
                        result5
                    }
                }
            }
            impl Interrupt {
                #[allow(unused_unsafe, clippy::all)]
                pub fn wait_until(
                    &self,
                    deadline_ns: u64,
                ) -> Result<Option<IrqEvent>, Error> {
                    unsafe {
                        #[repr(align(8))]
                        struct RetArea([::core::mem::MaybeUninit<u8>; 40]);
                        let mut ret_area = RetArea(
                            [::core::mem::MaybeUninit::uninit(); 40],
                        );
                        let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
                        #[cfg(target_arch = "wasm32")]
                        #[link(wasm_import_module = "drv:hardware/broker@0.1.0")]
                        unsafe extern "C" {
                            #[link_name = "[method]interrupt.wait-until"]
                            fn wit_import1(_: i32, _: i64, _: *mut u8);
                        }
                        #[cfg(not(target_arch = "wasm32"))]
                        unsafe extern "C" fn wit_import1(_: i32, _: i64, _: *mut u8) {
                            unreachable!()
                        }
                        unsafe {
                            wit_import1(
                                (self).handle() as i32,
                                _rt::as_i64(&deadline_ns),
                                ptr0,
                            )
                        };
                        let l2 = i32::from(*ptr0.add(0).cast::<u8>());
                        let result8 = match l2 {
                            0 => {
                                let e = {
                                    let l3 = i32::from(*ptr0.add(8).cast::<u8>());
                                    match l3 {
                                        0 => None,
                                        1 => {
                                            let e = {
                                                let l4 = *ptr0.add(16).cast::<i32>();
                                                let l5 = *ptr0.add(24).cast::<i64>();
                                                let l6 = *ptr0.add(32).cast::<i64>();
                                                IrqEvent {
                                                    vector: l4 as u32,
                                                    count: l5 as u64,
                                                    at_ns: l6 as u64,
                                                }
                                            };
                                            Some(e)
                                        }
                                        _ => _rt::invalid_enum_discriminant(),
                                    }
                                };
                                Ok(e)
                            }
                            1 => {
                                let e = {
                                    let l7 = i32::from(*ptr0.add(8).cast::<u8>());
                                    Error::_lift(l7 as u8)
                                };
                                Err(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        };
                        result8
                    }
                }
            }
            impl Device {
                #[allow(unused_unsafe, clippy::all)]
                pub fn generation(&self) -> u64 {
                    unsafe {
                        #[cfg(target_arch = "wasm32")]
                        #[link(wasm_import_module = "drv:hardware/broker@0.1.0")]
                        unsafe extern "C" {
                            #[link_name = "[method]device.generation"]
                            fn wit_import0(_: i32) -> i64;
                        }
                        #[cfg(not(target_arch = "wasm32"))]
                        unsafe extern "C" fn wit_import0(_: i32) -> i64 {
                            unreachable!()
                        }
                        let ret = unsafe { wit_import0((self).handle() as i32) };
                        ret as u64
                    }
                }
            }
            impl Device {
                #[allow(unused_unsafe, clippy::all)]
                pub fn open_region(&self, index: u8) -> Result<Region, Error> {
                    unsafe {
                        #[repr(align(4))]
                        struct RetArea([::core::mem::MaybeUninit<u8>; 8]);
                        let mut ret_area = RetArea(
                            [::core::mem::MaybeUninit::uninit(); 8],
                        );
                        let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
                        #[cfg(target_arch = "wasm32")]
                        #[link(wasm_import_module = "drv:hardware/broker@0.1.0")]
                        unsafe extern "C" {
                            #[link_name = "[method]device.open-region"]
                            fn wit_import1(_: i32, _: i32, _: *mut u8);
                        }
                        #[cfg(not(target_arch = "wasm32"))]
                        unsafe extern "C" fn wit_import1(_: i32, _: i32, _: *mut u8) {
                            unreachable!()
                        }
                        unsafe {
                            wit_import1(
                                (self).handle() as i32,
                                _rt::as_i32(&index),
                                ptr0,
                            )
                        };
                        let l2 = i32::from(*ptr0.add(0).cast::<u8>());
                        let result5 = match l2 {
                            0 => {
                                let e = {
                                    let l3 = *ptr0.add(4).cast::<i32>();
                                    unsafe { Region::from_handle(l3 as u32) }
                                };
                                Ok(e)
                            }
                            1 => {
                                let e = {
                                    let l4 = i32::from(*ptr0.add(4).cast::<u8>());
                                    Error::_lift(l4 as u8)
                                };
                                Err(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        };
                        result5
                    }
                }
            }
            impl Device {
                #[allow(unused_unsafe, clippy::all)]
                pub fn alloc_dma(
                    &self,
                    size: u32,
                    alignment: u32,
                    access: DmaAccess,
                ) -> Result<DmaArena, Error> {
                    unsafe {
                        #[repr(align(4))]
                        struct RetArea([::core::mem::MaybeUninit<u8>; 8]);
                        let mut ret_area = RetArea(
                            [::core::mem::MaybeUninit::uninit(); 8],
                        );
                        let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
                        #[cfg(target_arch = "wasm32")]
                        #[link(wasm_import_module = "drv:hardware/broker@0.1.0")]
                        unsafe extern "C" {
                            #[link_name = "[method]device.alloc-dma"]
                            fn wit_import1(_: i32, _: i32, _: i32, _: i32, _: *mut u8);
                        }
                        #[cfg(not(target_arch = "wasm32"))]
                        unsafe extern "C" fn wit_import1(
                            _: i32,
                            _: i32,
                            _: i32,
                            _: i32,
                            _: *mut u8,
                        ) {
                            unreachable!()
                        }
                        unsafe {
                            wit_import1(
                                (self).handle() as i32,
                                _rt::as_i32(&size),
                                _rt::as_i32(&alignment),
                                access.clone() as i32,
                                ptr0,
                            )
                        };
                        let l2 = i32::from(*ptr0.add(0).cast::<u8>());
                        let result5 = match l2 {
                            0 => {
                                let e = {
                                    let l3 = *ptr0.add(4).cast::<i32>();
                                    unsafe { DmaArena::from_handle(l3 as u32) }
                                };
                                Ok(e)
                            }
                            1 => {
                                let e = {
                                    let l4 = i32::from(*ptr0.add(4).cast::<u8>());
                                    Error::_lift(l4 as u8)
                                };
                                Err(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        };
                        result5
                    }
                }
            }
            impl Device {
                #[allow(unused_unsafe, clippy::all)]
                pub fn open_interrupt(&self, vector: u32) -> Result<Interrupt, Error> {
                    unsafe {
                        #[repr(align(4))]
                        struct RetArea([::core::mem::MaybeUninit<u8>; 8]);
                        let mut ret_area = RetArea(
                            [::core::mem::MaybeUninit::uninit(); 8],
                        );
                        let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
                        #[cfg(target_arch = "wasm32")]
                        #[link(wasm_import_module = "drv:hardware/broker@0.1.0")]
                        unsafe extern "C" {
                            #[link_name = "[method]device.open-interrupt"]
                            fn wit_import1(_: i32, _: i32, _: *mut u8);
                        }
                        #[cfg(not(target_arch = "wasm32"))]
                        unsafe extern "C" fn wit_import1(_: i32, _: i32, _: *mut u8) {
                            unreachable!()
                        }
                        unsafe {
                            wit_import1(
                                (self).handle() as i32,
                                _rt::as_i32(&vector),
                                ptr0,
                            )
                        };
                        let l2 = i32::from(*ptr0.add(0).cast::<u8>());
                        let result5 = match l2 {
                            0 => {
                                let e = {
                                    let l3 = *ptr0.add(4).cast::<i32>();
                                    unsafe { Interrupt::from_handle(l3 as u32) }
                                };
                                Ok(e)
                            }
                            1 => {
                                let e = {
                                    let l4 = i32::from(*ptr0.add(4).cast::<u8>());
                                    Error::_lift(l4 as u8)
                                };
                                Err(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        };
                        result5
                    }
                }
            }
            impl Device {
                #[allow(unused_unsafe, clippy::all)]
                pub fn reset(&self) -> Result<u64, Error> {
                    unsafe {
                        #[repr(align(8))]
                        struct RetArea([::core::mem::MaybeUninit<u8>; 16]);
                        let mut ret_area = RetArea(
                            [::core::mem::MaybeUninit::uninit(); 16],
                        );
                        let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
                        #[cfg(target_arch = "wasm32")]
                        #[link(wasm_import_module = "drv:hardware/broker@0.1.0")]
                        unsafe extern "C" {
                            #[link_name = "[method]device.reset"]
                            fn wit_import1(_: i32, _: *mut u8);
                        }
                        #[cfg(not(target_arch = "wasm32"))]
                        unsafe extern "C" fn wit_import1(_: i32, _: *mut u8) {
                            unreachable!()
                        }
                        unsafe { wit_import1((self).handle() as i32, ptr0) };
                        let l2 = i32::from(*ptr0.add(0).cast::<u8>());
                        let result5 = match l2 {
                            0 => {
                                let e = {
                                    let l3 = *ptr0.add(8).cast::<i64>();
                                    l3 as u64
                                };
                                Ok(e)
                            }
                            1 => {
                                let e = {
                                    let l4 = i32::from(*ptr0.add(8).cast::<u8>());
                                    Error::_lift(l4 as u8)
                                };
                                Err(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        };
                        result5
                    }
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn get_device() -> Device {
                unsafe {
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "drv:hardware/broker@0.1.0")]
                    unsafe extern "C" {
                        #[link_name = "get-device"]
                        fn wit_import0() -> i32;
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import0() -> i32 {
                        unreachable!()
                    }
                    let ret = unsafe { wit_import0() };
                    unsafe { Device::from_handle(ret as u32) }
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn now() -> u64 {
                unsafe {
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "drv:hardware/broker@0.1.0")]
                    unsafe extern "C" {
                        #[link_name = "now"]
                        fn wit_import0() -> i64;
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import0() -> i64 {
                        unreachable!()
                    }
                    let ret = unsafe { wit_import0() };
                    ret as u64
                }
            }
        }
    }
}
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod drv {
        pub mod hardware {
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod probe {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                pub type Error = super::super::super::super::drv::hardware::broker::Error;
                #[repr(C)]
                #[derive(Clone, Copy)]
                pub struct Report {
                    pub generation_before: u64,
                    pub generation_after: u64,
                    pub iova: u64,
                    pub interrupt_count: u64,
                    pub interrupt_at_ns: u64,
                    pub dma_round_trip: bool,
                    pub device_dma_observed: bool,
                    pub bounds_rejected: bool,
                    pub bar_bounds_rejected: bool,
                    pub stale_rejected: bool,
                    pub region_stale_rejected: bool,
                }
                impl ::core::fmt::Debug for Report {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("Report")
                            .field("generation-before", &self.generation_before)
                            .field("generation-after", &self.generation_after)
                            .field("iova", &self.iova)
                            .field("interrupt-count", &self.interrupt_count)
                            .field("interrupt-at-ns", &self.interrupt_at_ns)
                            .field("dma-round-trip", &self.dma_round_trip)
                            .field("device-dma-observed", &self.device_dma_observed)
                            .field("bounds-rejected", &self.bounds_rejected)
                            .field("bar-bounds-rejected", &self.bar_bounds_rejected)
                            .field("stale-rejected", &self.stale_rejected)
                            .field("region-stale-rejected", &self.region_stale_rejected)
                            .finish()
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_run_cabi<T: Guest>() -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::run();
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result0 {
                        Ok(e) => {
                            *ptr1.add(0).cast::<u8>() = (0i32) as u8;
                            let Report {
                                generation_before: generation_before2,
                                generation_after: generation_after2,
                                iova: iova2,
                                interrupt_count: interrupt_count2,
                                interrupt_at_ns: interrupt_at_ns2,
                                dma_round_trip: dma_round_trip2,
                                device_dma_observed: device_dma_observed2,
                                bounds_rejected: bounds_rejected2,
                                bar_bounds_rejected: bar_bounds_rejected2,
                                stale_rejected: stale_rejected2,
                                region_stale_rejected: region_stale_rejected2,
                            } = e;
                            *ptr1.add(8).cast::<i64>() = _rt::as_i64(generation_before2);
                            *ptr1.add(16).cast::<i64>() = _rt::as_i64(generation_after2);
                            *ptr1.add(24).cast::<i64>() = _rt::as_i64(iova2);
                            *ptr1.add(32).cast::<i64>() = _rt::as_i64(interrupt_count2);
                            *ptr1.add(40).cast::<i64>() = _rt::as_i64(interrupt_at_ns2);
                            *ptr1.add(48).cast::<u8>() = (match dma_round_trip2 {
                                true => 1,
                                false => 0,
                            }) as u8;
                            *ptr1.add(49).cast::<u8>() = (match device_dma_observed2 {
                                true => 1,
                                false => 0,
                            }) as u8;
                            *ptr1.add(50).cast::<u8>() = (match bounds_rejected2 {
                                true => 1,
                                false => 0,
                            }) as u8;
                            *ptr1.add(51).cast::<u8>() = (match bar_bounds_rejected2 {
                                true => 1,
                                false => 0,
                            }) as u8;
                            *ptr1.add(52).cast::<u8>() = (match stale_rejected2 {
                                true => 1,
                                false => 0,
                            }) as u8;
                            *ptr1.add(53).cast::<u8>() = (match region_stale_rejected2 {
                                true => 1,
                                false => 0,
                            }) as u8;
                        }
                        Err(e) => {
                            *ptr1.add(0).cast::<u8>() = (1i32) as u8;
                            *ptr1.add(8).cast::<u8>() = (e.clone() as i32) as u8;
                        }
                    };
                    ptr1
                }
                pub trait Guest {
                    fn run() -> Result<Report, Error>;
                }
                #[doc(hidden)]
                macro_rules! __export_drv_hardware_probe_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "drv:hardware/probe@0.1.0#run")] unsafe extern "C" fn
                        export_run() -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_run_cabi::<$ty > () } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_drv_hardware_probe_0_1_0_cabi;
                #[repr(align(8))]
                struct _RetArea([::core::mem::MaybeUninit<u8>; 56]);
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 56],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    use core::fmt;
    use core::marker;
    use core::sync::atomic::{AtomicU32, Ordering::Relaxed};
    /// A type which represents a component model resource, either imported or
    /// exported into this component.
    ///
    /// This is a low-level wrapper which handles the lifetime of the resource
    /// (namely this has a destructor). The `T` provided defines the component model
    /// intrinsics that this wrapper uses.
    ///
    /// One of the chief purposes of this type is to provide `Deref` implementations
    /// to access the underlying data when it is owned.
    ///
    /// This type is primarily used in generated code for exported and imported
    /// resources.
    #[repr(transparent)]
    pub struct Resource<T: WasmResource> {
        handle: AtomicU32,
        _marker: marker::PhantomData<T>,
    }
    /// A trait which all wasm resources implement, namely providing the ability to
    /// drop a resource.
    ///
    /// This generally is implemented by generated code, not user-facing code.
    #[allow(clippy::missing_safety_doc)]
    pub unsafe trait WasmResource {
        /// Invokes the `[resource-drop]...` intrinsic.
        unsafe fn drop(handle: u32);
    }
    impl<T: WasmResource> Resource<T> {
        #[doc(hidden)]
        pub unsafe fn from_handle(handle: u32) -> Self {
            debug_assert!(handle != u32::MAX);
            Self {
                handle: AtomicU32::new(handle),
                _marker: marker::PhantomData,
            }
        }
        /// Takes ownership of the handle owned by `resource`.
        ///
        /// Note that this ideally would be `into_handle` taking `Resource<T>` by
        /// ownership. The code generator does not enable that in all situations,
        /// unfortunately, so this is provided instead.
        ///
        /// Also note that `take_handle` is in theory only ever called on values
        /// owned by a generated function. For example a generated function might
        /// take `Resource<T>` as an argument but then call `take_handle` on a
        /// reference to that argument. In that sense the dynamic nature of
        /// `take_handle` should only be exposed internally to generated code, not
        /// to user code.
        #[doc(hidden)]
        pub fn take_handle(resource: &Resource<T>) -> u32 {
            resource.handle.swap(u32::MAX, Relaxed)
        }
        #[doc(hidden)]
        pub fn handle(resource: &Resource<T>) -> u32 {
            resource.handle.load(Relaxed)
        }
    }
    impl<T: WasmResource> fmt::Debug for Resource<T> {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
            f.debug_struct("Resource").field("handle", &self.handle).finish()
        }
    }
    impl<T: WasmResource> Drop for Resource<T> {
        fn drop(&mut self) {
            unsafe {
                match self.handle.load(Relaxed) {
                    u32::MAX => {}
                    other => T::drop(other),
                }
            }
        }
    }
    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }
    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }
    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }
    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    pub unsafe fn invalid_enum_discriminant<T>() -> T {
        if cfg!(debug_assertions) {
            panic!("invalid enum discriminant")
        } else {
            unsafe { core::hint::unreachable_unchecked() }
        }
    }
    pub use alloc_crate::vec::Vec;
    pub fn as_i64<T: AsI64>(t: T) -> i64 {
        t.as_i64()
    }
    pub trait AsI64 {
        fn as_i64(self) -> i64;
    }
    impl<'a, T: Copy + AsI64> AsI64 for &'a T {
        fn as_i64(self) -> i64 {
            (*self).as_i64()
        }
    }
    impl AsI64 for i64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    impl AsI64 for u64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_driver_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::drv::hardware::probe::__export_drv_hardware_probe_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::drv::hardware::probe);
    };
}
#[doc(inline)]
pub(crate) use __export_driver_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(link_section = "component-type:wit-bindgen:0.41.0:drv:hardware@0.1.0:driver:encoded world")]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 1402] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xfd\x09\x01A\x02\x01\
A\x05\x01B8\x01m\x06\x07invalid\x0cstale-handle\x0dout-of-bounds\x05limit\x09can\
celled\x0cdevice-fault\x04\0\x05error\x03\0\0\x01m\x03\x0bdevice-read\x0cdevice-\
write\x0dbidirectional\x04\0\x0adma-access\x03\0\x02\x01r\x03\x06vectory\x05coun\
tw\x05at-nsw\x04\0\x09irq-event\x03\0\x04\x04\0\x06region\x03\x01\x04\0\x09dma-a\
rena\x03\x01\x04\0\x09interrupt\x03\x01\x04\0\x06device\x03\x01\x01h\x06\x01j\x01\
y\x01\x01\x01@\x02\x04self\x0a\x06offsety\0\x0b\x04\0\x17[method]region.read-u32\
\x01\x0c\x01j\0\x01\x01\x01@\x03\x04self\x0a\x06offsety\x05valuey\0\x0d\x04\0\x18\
[method]region.write-u32\x01\x0e\x01h\x07\x01@\x01\x04self\x0f\0\x0b\x04\0\x18[m\
ethod]dma-arena.length\x01\x10\x01j\x01w\x01\x01\x01@\x01\x04self\x0f\0\x11\x04\0\
\x16[method]dma-arena.iova\x01\x12\x01p}\x01j\x01\x13\x01\x01\x01@\x03\x04self\x0f\
\x06offsety\x06lengthy\0\x14\x04\0\x16[method]dma-arena.read\x01\x15\x01@\x03\x04\
self\x0f\x06offsety\x05bytes\x13\0\x0d\x04\0\x17[method]dma-arena.write\x01\x16\x01\
h\x08\x01k\x05\x01j\x01\x18\x01\x01\x01@\x02\x04self\x17\x0bdeadline-nsw\0\x19\x04\
\0\x1c[method]interrupt.wait-until\x01\x1a\x01h\x09\x01@\x01\x04self\x1b\0w\x04\0\
\x19[method]device.generation\x01\x1c\x01i\x06\x01j\x01\x1d\x01\x01\x01@\x02\x04\
self\x1b\x05index}\0\x1e\x04\0\x1a[method]device.open-region\x01\x1f\x01i\x07\x01\
j\x01\x20\x01\x01\x01@\x04\x04self\x1b\x04sizey\x09alignmenty\x06access\x03\0!\x04\
\0\x18[method]device.alloc-dma\x01\"\x01i\x08\x01j\x01#\x01\x01\x01@\x02\x04self\
\x1b\x06vectory\0$\x04\0\x1d[method]device.open-interrupt\x01%\x01@\x01\x04self\x1b\
\0\x11\x04\0\x14[method]device.reset\x01&\x01i\x09\x01@\0\0'\x04\0\x0aget-device\
\x01(\x01@\0\0w\x04\0\x03now\x01)\x03\0\x19drv:hardware/broker@0.1.0\x05\0\x02\x03\
\0\0\x05error\x01B\x07\x02\x03\x02\x01\x01\x04\0\x05error\x03\0\0\x01r\x0b\x11ge\
neration-beforew\x10generation-afterw\x04iovaw\x0finterrupt-countw\x0finterrupt-\
at-nsw\x0edma-round-trip\x7f\x13device-dma-observed\x7f\x0fbounds-rejected\x7f\x13\
bar-bounds-rejected\x7f\x0estale-rejected\x7f\x15region-stale-rejected\x7f\x04\0\
\x06report\x03\0\x02\x01j\x01\x03\x01\x01\x01@\0\0\x04\x04\0\x03run\x01\x05\x04\0\
\x18drv:hardware/probe@0.1.0\x05\x02\x04\0\x19drv:hardware/driver@0.1.0\x04\0\x0b\
\x0c\x01\0\x06driver\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-comp\
onent\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
