[package]
name = "netstack3_core"
edition.workspace = true
license.workspace = true
version.workspace = true
[features]
instrumented = ["netstack3_base/instrumented", "netstack3_datagram/instrumented", "netstack3_device/instrumented", "netstack3_filter/instrumented", "netstack3_icmp_echo/instrumented", "netstack3_ip/instrumented", "netstack3_sync/instrumented", "netstack3_tcp/instrumented", "netstack3_udp/instrumented"]
testutils = ["instrumented", "netstack3_base/testutils", "netstack3_datagram/testutils", "netstack3_device/testutils", "netstack3_filter/testutils", "netstack3_icmp_echo/testutils", "netstack3_ip/testutils", "netstack3_sync/testutils", "netstack3_tcp/testutils", "netstack3_udp/testutils"]
[dependencies]
assert_matches.workspace = true
derivative.workspace = true
lock_order.workspace = true
log.workspace = true
net_types.workspace = true
netstack3_base.workspace = true
netstack3_datagram.workspace = true
netstack3_device.workspace = true
netstack3_filter.workspace = true
netstack3_hashmap.workspace = true
netstack3_icmp_echo.workspace = true
netstack3_ip.workspace = true
netstack3_macros.workspace = true
netstack3_sync.workspace = true
netstack3_tcp.workspace = true
netstack3_trace.workspace = true
netstack3_udp.workspace = true
packet.workspace = true
packet_formats.workspace = true
zerocopy.workspace = true
