[package]
name = "ath11k-wifi-service"
description = "Sandboxed WCN6750 Wi-Fi service composition"
edition = "2024"
license = "GPL-2.0-only"
version = "0.1.0"

[workspace]
resolver = "3"

[dependencies]
drv-network-service = { path = "../../../../net/network-service" }
ath11k-core = { path = "../ath11k-core" }
ath11k-qmi-qrtr = { path = "../ath11k-qmi-qrtr" }
ath11k-softmac-adapter = { path = "../ath11k-softmac-adapter" }
drv-hardware = { path = "../../../../platform/hardware-api" }
drv-hardware-backends = { path = "../../../../platform/hardware-backends" }
fidl-fuchsia-wlan-common = { path = "../../../../../reference/fuchsia-1e1219e3fac944c9a906aea9646939746b6062b3/sdk/fidl/fuchsia.wlan.common" }
fidl-fuchsia-wlan-ieee80211 = { path = "../../../../../reference/fuchsia-1e1219e3fac944c9a906aea9646939746b6062b3/sdk/fidl/fuchsia.wlan.ieee80211" }
fidl-fuchsia-wlan-internal = { path = "../../../../../reference/fuchsia-1e1219e3fac944c9a906aea9646939746b6062b3/sdk/fidl/fuchsia.wlan.internal" }
fidl-fuchsia-wlan-mlme = { path = "../../../../../reference/fuchsia-1e1219e3fac944c9a906aea9646939746b6062b3/sdk/fidl/fuchsia.wlan.mlme" }
fidl-fuchsia-wlan-sme = { path = "../../../../../reference/fuchsia-1e1219e3fac944c9a906aea9646939746b6062b3/sdk/fidl/fuchsia.wlan.sme" }
fuchsia-inspect = { path = "../../../../../reference/fuchsia-1e1219e3fac944c9a906aea9646939746b6062b3/src/lib/diagnostics/inspect/rust" }
futures = "=0.3.32"
libc = "=0.2.189"
linux-self-sandbox = { path = "../../../../platform/linux-self-sandbox" }
qrtr-socket = { path = "../../../../qualcomm/qrtr-socket" }
userspace-vfio = { path = "../../../../platform/userspace-vfio" }
wifi-control-service = { path = "../../../wifi-control-service" }
wifi-supervisor-wire = { path = "../../../wifi-supervisor-wire" }
wlan-control-wire = { path = "../../../wlan-control-wire" }
wlan-mlme = { path = "../../../../../reference/fuchsia-1e1219e3fac944c9a906aea9646939746b6062b3/src/connectivity/wlan/lib/mlme/rust" }
wlan-sme = { path = "../../../../../reference/fuchsia-1e1219e3fac944c9a906aea9646939746b6062b3/src/connectivity/wlan/lib/sme" }
wlan-softmac-host = { path = "../../../wlan-softmac-host" }

[patch.crates-io]
trust-dns-proto = { path = "../../../../../reference/fuchsia-1e1219e3fac944c9a906aea9646939746b6062b3/third_party/rust_crates/forks/trust-dns-proto-0.22.0" }
trust-dns-resolver = { path = "../../../../../reference/fuchsia-1e1219e3fac944c9a906aea9646939746b6062b3/third_party/rust_crates/forks/trust-dns-resolver-0.22.0" }
