[package]
name = "drv-network-service"
description = "Sandboxed native Netstack3 service and owned-application networking"
edition = "2024"
license = "GPL-2.0-only"
version = "0.1.0"

[workspace]
resolver = "3"

[dependencies]
netstack3-port-integration = { path = "../../reference/fuchsia-1e1219e3fac944c9a906aea9646939746b6062b3/src/connectivity/network/netstack3/cargo/port-integration" }
netstack3-port-spike = { path = "../netstack3-port-spike" }
rand = "=0.9.4"

[dev-dependencies]
dhcp-protocol = { path = "../../reference/fuchsia-1e1219e3fac944c9a906aea9646939746b6062b3/src/connectivity/network/dhcpv4/protocol" }
net_types = { path = "../../reference/fuchsia-1e1219e3fac944c9a906aea9646939746b6062b3/src/connectivity/lib/net-types" }
netstack3_base = { path = "../../reference/fuchsia-1e1219e3fac944c9a906aea9646939746b6062b3/src/connectivity/network/netstack3/core/base" }
packet = { path = "../../reference/fuchsia-1e1219e3fac944c9a906aea9646939746b6062b3/src/lib/network/packet" }
packet_formats = { path = "../../reference/fuchsia-1e1219e3fac944c9a906aea9646939746b6062b3/src/connectivity/lib/packet-formats" }
wlan-softmac-host = { path = "../wlan-softmac-host" }

[patch.crates-io]
trust-dns-proto = { path = "../../reference/fuchsia-1e1219e3fac944c9a906aea9646939746b6062b3/third_party/rust_crates/forks/trust-dns-proto-0.22.0" }
trust-dns-resolver = { path = "../../reference/fuchsia-1e1219e3fac944c9a906aea9646939746b6062b3/third_party/rust_crates/forks/trust-dns-resolver-0.22.0" }
