[package]
name = "netstack3_ip"
edition.workspace = true
license.workspace = true
version.workspace = true
[features]
instrumented = ["netstack3_base/instrumented", "netstack3_filter/instrumented"]
testutils = ["instrumented", "netstack3_base/testutils", "netstack3_filter/testutils"]
[dependencies]
arrayvec.workspace = true
assert_matches.workspace = true
derivative.workspace = true
diagnostics_traits.workspace = true
either.workspace = true
explicit.workspace = true
hmac.workspace = true
lock_order.workspace = true
log.workspace = true
lru-cache.workspace = true
net_declare.workspace = true
net_types.workspace = true
netstack3_base.workspace = true
netstack3_filter.workspace = true
netstack3_hashmap.workspace = true
netstack3_macros.workspace = true
netstack3_trace.workspace = true
packet.workspace = true
packet_formats.workspace = true
rand.workspace = true
ref-cast.workspace = true
sha2.workspace = true
thiserror.workspace = true
zerocopy.workspace = true
