[package]
name = "wlan-sme"
workspace = "../../../network/netstack3"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
path = "src/lib.rs"
doctest = false

[dependencies]
anyhow.workspace = true
eapol = { path = "../eapol" }
fidl.workspace = true
fidl-fuchsia-wlan-common = { path = "../../../../../sdk/fidl/fuchsia.wlan.common" }
fidl-fuchsia-wlan-ieee80211 = { path = "../../../../../sdk/fidl/fuchsia.wlan.ieee80211" }
fidl-fuchsia-wlan-internal = { path = "../../../../../sdk/fidl/fuchsia.wlan.internal" }
fidl-fuchsia-wlan-mlme = { path = "../../../../../sdk/fidl/fuchsia.wlan.mlme" }
fidl-fuchsia-wlan-sme = { path = "../../../../../sdk/fidl/fuchsia.wlan.sme" }
fidl-fuchsia-wlan-stats = { path = "../../../../../sdk/fidl/fuchsia.wlan.stats" }
fuchsia-inspect = { path = "../../../../lib/diagnostics/inspect/rust" }
fuchsia-inspect-contrib = { path = "../../../../lib/diagnostics/inspect/contrib/rust" }
fuchsia-sync.workspace = true
futures.workspace = true
ieee80211.workspace = true
log.workspace = true
thiserror.workspace = true
wlan-common = { path = "../common/rust", features = ["host_test_utils"] }
wlan_rsn.workspace = true
wlan_statemachine.workspace = true
zx = { path = "../../../../../sdk/rust/zx" }

[features]
fuchsia-transport = []
