[package]
name = "wlan-fcg-crypto"
workspace = "../../../network/netstack3"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
anyhow.workspace = true
bssl-sys = { path = "../../../../../third_party/boringssl/rust/bssl-sys" }
fidl_fuchsia_wlan_ieee80211 = { package = "fidl-fuchsia-wlan-ieee80211", path = "../../../../../sdk/fidl/fuchsia.wlan.ieee80211" }
ieee80211.workspace = true
log.workspace = true
mundane.workspace = true
num.workspace = true
num-derive.workspace = true
num-traits.workspace = true
wlan-common = { path = "../common/rust" }
wlan_statemachine.workspace = true

[dev-dependencies]
assert_matches.workspace = true
hex.workspace = true
test-case = "=3.3.1"
