[package]
name = "bluetooth-sapphire-wasm"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bluetooth-hci-broker = { path = "../bluetooth-hci-broker" }
libc = "0.2.189"
wasmtime = { version = "47.0.2", default-features = false, features = [
  "cranelift",
  "runtime",
  "std",
  "winch",
] }

[dev-dependencies]
wat = "1.245.1"
