[package]
name = "fidl-fuchsia-wlan-mlme"
workspace = "../../../src/connectivity/network/netstack3"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "fidl_fuchsia_wlan_mlme"
path = "src/lib.rs"

[dependencies]
fidl-fuchsia-wlan-common = { path = "../fuchsia.wlan.common" }
fidl-fuchsia-wlan-ieee80211 = { path = "../fuchsia.wlan.ieee80211" }
fidl-fuchsia-wlan-internal = { path = "../fuchsia.wlan.internal" }
fidl-fuchsia-wlan-minstrel = { path = "../fuchsia.wlan.minstrel" }
fidl-fuchsia-wlan-stats = { path = "../fuchsia.wlan.stats" }
