[package]
name = "ieee80211"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
path = "src/lib.rs"
doctest = false

[dependencies]
anyhow.workspace = true
arbitrary.workspace = true
fidl-fuchsia-wlan-ieee80211 = { path = "../../../../../sdk/fidl/fuchsia.wlan.ieee80211" }
hex.workspace = true
thiserror.workspace = true
zerocopy.workspace = true
