[package]
name="ath11k-ce"
version.workspace=true
edition.workspace=true
license.workspace=true
[dependencies]
ath11k-hal={path="../ath11k-hal"}
ath11k-platform-backend={path="../ath11k-platform-backend"}
[dev-dependencies]
drv-hardware-backends={path="../../../../platform/hardware-backends"}
proptest="1"
